### PR TITLE
Fixing SSL_verify_mode deprecated warning.

### PR DESCRIPTION
**Pull request by digrouz**
Fixing SSL_verify_mode deprecated warning:
*******************************************************************
 Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
 is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
 together with SSL_ca_file|SSL_ca_path for verification.
 If you really don't want to verify the certificate and keep the
 connection open to Man-In-The-Middle attacks please set
 SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
*******************************************************************

### CODE REVIEW

**Comment by wimpunk** [comment]
The idea is good but fortunately there are mis-configured SSL servers out there.  Nowadays most providers are configured correctly but routers mostly have wrong certificates. The user should still have the possibility to use the SSL_VERIFY_NONE when he knows what he's doing.  He should also have the possibility to specify the location of the ca_file or ca_path.

**Comment by digrouz** [comment]
You mean I need to add options for SSL_VERIFY_NONE and for ca_path ?

**Comment by DaveSophoServices** [comment]
Will try to implement this with a flag for disabling the SSL_VERIFY code.

**Comment by SuperSandro2000** [comment]
This is not shown for me on Ubuntu. Did the package change this behavior and deprecated the default mode?

**Comment by mike2307** [comment]
I'm using RHEL 7 with the package perl-IO-Socket-SSL.noarch 1.94-7.el7

I get the same warning. To fix it, it have to add
`SSL_verify_mode => 1,`
instead.

It won't let me use a string or a constant.

**Comment by dkerr64** [comment]
I believe that this would be fixed with PR #233 which includes new option for `-{no}web-ssl-validate` (in both the curl and non-curl code path).

**Comment by SuperSandro2000** [comment]
Closing in favor of #233

**Comment by dkerr64** [comment]
Shouldn't the issue remain open until after the PR is merged?

**Comment by SuperSandro2000** [comment]
Well, maybe but it is a pull request which isn't mergable since a long time and the opener did not respond, so I think we can keep it closed.

**Comment by dkerr64** [comment]
> Well, maybe but it is a pull request which isn't mergable since a long time and the opener did not respond, so I think we can keep it closed.

Ah... my mistake, I thought this was an issue but is in fact a PR.  So yes, close out old non-mergeable PRs in favor of the one that can merge.

**Pull request closed without merging**
