### PR TITLE
Install findutils on Fedora

### PR DESCRIPTION
**Pull request by rhansen**

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Why do we need this?

**Comment by rhansen** [comment]
`make distcheck` uses `find`. Surprisingly it doesn't fail despite all the `find: command not found` errors.

**Comment by SuperSandro2000** [comment]
> `make distcheck` uses `find`. Surprisingly it doesn't fail despite all the `find: command not found` errors.

Didn't notice that either. Can we somehow make sure this is not failing in the future? Some sort of requirement on that binary?

**Comment by rhansen** [comment]
`find` is specified by POSIX, so *every* Unix-ish operating system *should* have it. The lack of `find` is almost as offensive to me as leaving out `ls`. It's so common that Autoconf itself doesn't bother checking for it. I don't think it's worth adding an check for it in our `configure.ac`.

**Pull request merged**
