### PR TITLE
Feature provider ydns

### PR DESCRIPTION
**Pull request by DaCookie4u**
This is the a first implementation of the ydns.io api. See https://ydns.io/api/v1/.

I tested it on my local machine and an OPNsense firewall and it works fine for ipv4 and/or ipv6.

Not sure what else to put into the request. But hopefully you merge it in, so it goes downstream to OPNsense at some point.

### CODE REVIEW

**Comment by LenardHess** [comment]
Looks good on first glance, will take a more detailed look in the coming days.

**Comment by LenardHess** [comment]
We will leave this pull request open until v3.11.0 has been released (see https://github.com/ddclient/ddclient/issues/552#issuecomment-1675925270 for details). It will get pulled into v3.11.1

**Comment by LenardHess** [comment]
With v3.11.0 released, please rebase this onto master for the merge.

One nitpick that have: Can you change the login and password placeholder strings to "your-username" and "your-password"? Seeing the partially random strings when glancing over activates  my secret-in-code alarms

**Comment by DaCookie4u** [comment]
Updated to current master and changed the pseudo credentials.

**Comment by LenardHess** [comment]
Thanks! But please rebase on top of master instead of merging master into your branch.

**Pull request closed without merging**
