### PR TITLE
Gandi: Add support for personal access tokens.

### PR DESCRIPTION
**Pull request by catwith1hat**

### CODE REVIEW

**Comment by LenardHess** [comment]
Hello,
the gandi API update has already been done in this commit (a57cb3b). See also #602 for more

**Comment by catwith1hat** [comment]
The comments in #602 wrong. API keys still work. So you just surprise broke all your Gandi users with the other backward incompatible PR. I would revert the other PR and merge this one before you cut a new release. But that's your choice.

**Comment by LenardHess** [comment]
In that case I'll get #626 reverted then and this one looked at, thanks for the info :+1:

**Comment by LenardHess** [comment]
I do not want the password string to have a magic prefix - especially considering that when (if?) gandi kills the support for API keys, we want to remove support for the old method and make the PAT method the only one available. Having those updates affect the details on how to format the password entry is messy.

I tried a different route in #626 - using a separate config bool variable.

**Comment by rhansen** [comment]
See <https://github.com/ddclient/ddclient/issues/602#issuecomment-2002133559> for additional alternative approaches.

**Comment by LenardHess** [comment]
Merged #636, closing this one

**Pull request closed without merging**
