### PR TITLE
Truncate freedns passwords longer than 16 chars

### LINKED ISSUE #176: freedns.afraid.org not working
```
protocol=freedns
server=freedns.afraid.org
login=username
password='password'
domain1,domain2,domain3


DEBUG:
DEBUG:     nic_freedns_update -------------------
DEBUG:    proxy  =
DEBUG:    url    = http://freedns.afraid.org/api/?action=getdyndns&sha=XXXXXXXXXXXX
DEBUG:    server = freedns.afraid.org
CONNECT:  freedns.afraid.org
CONNECTED:  using SSL
SENDING:  GET /api/?action=getdyndns&sha=XXXXXXXXXXX
HTTP/1.0
SENDING:   Host: freedns.afraid.org
SENDING:   User-Agent: ddclient/3.9.1
SENDING:   Connection: close
SENDING:
SENDING:
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Server: nginx
RECEIVE:  Date: Sat, 13 Jun 2020 21:27:26 GMT
RECEIVE:  Content-Type: text/html; charset=UTF-8
RECEIVE:  Connection: close
RECEIVE:  Vary: Accept-Encoding
RECEIVE:  X-Cache: MISS
RECEIVE:
RECEIVE:  ERROR: Could not authenticate.
FAILED:   Could not get freedns update URLs from freedns.afraid.org
```

### PR DESCRIPTION
**Pull request by rhansen**
Fixes #176

### CODE REVIEW

**Comment by rhansen** [comment]
@th3gr33n: Can you try this out and let me know if it fixes it?

**Comment by th3gr33n** [comment]
yes truncating my password to 16 signs worked.
looks like even the website is doing this thats why i could login there.

**Comment by rhansen** [comment]
Great!

Did you test it by running this updated script? Or did you update your config to truncate the password yourself? (I don't want to merge this PR until someone else has tested or reviewed it.)

**Comment by th3gr33n** [comment]
Hi i've truncated myself.

Tryd your version know with longer password.
giving me an error 
`Scalar found where operator expected at /usr/sbin/ddclient line 3851, near ")
    $url"
        (Missing operator before $url?)
syntax error at /usr/sbin/ddclient line 3851, near ")
    $url "
Global symbol "$hashed_creds" requires explicit package name (did you forget to declare "my $hashed_creds"?) at /usr/sbin/ddclient line 3851.
Execution of /usr/sbin/ddclient aborted due to compilation errors.
`

**Comment by rhansen** [comment]
Whoops, missed a semicolon. I though I tested it myself, but I accidentally ran `ddclient` rather than `./ddclient` so it ran the ddclient from my PATH instead of from my Git working directory.  Doh!

Thanks for testing, and thanks for the bug report!

**Comment by th3gr33n** [comment]
seems not to work

`CONNECT:  freedns.afraid.org
CONNECTED:  using SSL
SENDING:  GET /nic/update?hostname=HOSTNAME&ip=X:X:X:X HTTP/1.0
SENDING:  Host: freedns.afraid.org
SENDING:  Authorization: Basic XXXXXXXXXXXX
SENDING:  User-Agent: ddclient/3.9.1
SENDING:  Connection: close
SENDING:
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Server: nginx
RECEIVE:  Date: Tue, 16 Jun 2020 19:44:48 GMT
RECEIVE:  Content-Type: text/plain;charset=UTF-8
RECEIVE:  Connection: close
RECEIVE:  Vary: Accept-Encoding
RECEIVE:  X-Cache: MISS
RECEIVE:
RECEIVE:  ERROR: Unable to locate this record (changed password recently? deleted and re-created this dns entry?) (double check username/password are correct)
WARNING:  REPLIED: HTTP/1.1 200 OK
WARNING:  Server: nginx
WARNING:  Date: Tue, 16 Jun 2020 19:44:48 GMT
WARNING:  Content-Type: text/plain;charset=UTF-8
WARNING:  Connection: close
WARNING:  Vary: Accept-Encoding
WARNING:  X-Cache: MISS
WARNING:
WARNING:  ERROR: Unable to locate this record (changed password recently? deleted and re-created this dns entry?) (double check username/password are correct)
FAILED:   updating hostname: Invalid reply.
`

when truncating password again it works

**Comment by rhansen** [comment]
Can you paste your full (censored) config? Based on the URL in the verbose output you provided it looks like you're not setting `protocol=freedns`.

**Comment by th3gr33n** [comment]
yeah my bad setting password back to truncated got me a type in the config.
working now with and without truncated password.

**Comment by rhansen** [comment]
I'm going to close this without merging due to https://github.com/ddclient/ddclient/issues/176#issuecomment-644996710

**Pull request closed without merging**
