### PR TITLE
Cleanup of ddclient source.

### PR DESCRIPTION
**Pull request by nelsonjr**

### CODE REVIEW

**Comment by wimpunk** [comment]
Can you tell me which coding style you used because you really changed *a lot* of code.  With code cleaning I meant making all look the same and cleanup some blanks at the end of the lines, not restyling the whole program.

**Comment by nelsonjr** [comment]
Sorry I went overboard :-) Other than the shock of so many changes, what was your opinion to the code style and organization? Did you like it?

After going through the program fixing them top to bottom, I started finding it hard to keep the style consistent all throughout, so I tried to find a good automated formatter...

I found an interesting script, called "perltidy", that can style the program automatically. I actually did some manual adjustments after running it, but it can be customized so you have a file with the style rules of your likings, so anyone can simply reapply it.

**Comment by nelsonjr** [comment]
Ping? Did not hear from you about the reformat + using the tool. Please let me know.

**Comment by wimpunk** [comment]
Like I said earlier:
> With code cleaning I meant making all look the same and cleanup some blanks at the end of the lines, not restyling the whole program.

Restyling the program that hard would break the patches package maintainers use downstream so I will keep using vim as my code styler.  Although you made a good point that it needs some cleaning.

**Comment by nelsonjr** [comment]
Sounds good. I will make another patch less radical and send your way.

**Comment by wimpunk** [comment]
Hold your horses. I'm getting an idea. Give me a few days to work it out. Can you subscribe to the ddclient mailing list on https://lists.sourceforge.net/lists/listinfo/ddclient-support so we can discuss it.  Maybe the other developers will help to.

**Comment by nelsonjr** [comment]
Sure. Signed up.


Best regards,
-- Nelson

**Comment by nelsonjr** [comment]
Hi,

What was the conclusion of this effort? Should I close this PR or should I refresh it with latest cleanup? I could not find anything on the mailing list about it.

**Comment by wimpunk** [comment]
Sorry, I got a little busy and didn't worked very much on ddclient during the last months.  I'll try to get on this pretty soon.

**Comment by DaveSophoServices** [comment]
I'm coming on to help maintain the project. @nelsonjr it has been a long time since you originally submitted this request. I've not used github pull requests before, but it looks like that github wants to merge all your original formatting requests and the newer ones. If you look at the "Files Changed", does it accurately depict the changes you're wanting, or a combination of the first attempt, and the later attempts?

**Comment by SuperSandro2000** [comment]
@DaveSophoServices GitHub wants to merge all commits that you can see in the commits tab https://github.com/ddclient/ddclient/pull/14/commits

The problem with this PR right now is that it needs a rebase because it is just to old and git can't merge it cleanly.

**Comment by SuperSandro2000** [comment]
#120 is basically replacing this and also using perltidy. If there are parts which you tidied up and where not changed in that PR please open a new PR with those changes. I did a quick look at the changes here and did not find relevant ones the fast. I am sure I missed some.

**Pull request closed without merging**
