### PR TITLE
Add DDNS.FM support

### PR DESCRIPTION
**Pull request by woolflare**
Add a free DDNS provider ddns.fm

### CODE REVIEW

**Comment by rhansen** [comment]
Thanks for the contribution!

The docs don't say whether IPv4 and IPv6 addresses can be updated simultaneously, or if setting IPv4 erases the IPv6 record and vice-versa.  Can you test it?  For example:

```
curl "https://api.ddns.fm/update?key=${DDNSFM_KEY:?}&domain=${DDNSFM_DOMAIN:?}&myip=192.0.2.1,2001:db8::1"
```

**Comment by woolflare** [comment]
> Thanks for the contribution!
> 
> The docs don't say whether IPv4 and IPv6 addresses can be updated simultaneously, or if setting IPv4 erases the IPv6 record and vice-versa. Can you test it? For example:
> 
> ```
> curl "https://api.ddns.fm/update?key=${DDNSFM_KEY:?}&domain=${DDNSFM_DOMAIN:?}&myip=192.0.2.1,2001:db8::1"
> ```
IPv4 and IPv6 cannot be updated simultaneously; only one IP address can be passed at a time. The system will automatically determine whether it is IPv4 or IPv6. Updating IPv4 will not delete IPv6 records. A and AAAA records are independent of each other.

**Comment by rhansen** [comment]
Thanks for checking.  I rebased onto latest `master` and pushed a few fixup commits.  Please review and test my changes and let me know if everything looks OK.  If so, I'll squash all the commits together and merge.

**Comment by woolflare** [comment]
> Thanks for checking. I rebased onto latest `master` and pushed a few fixup commits. Please review and test my changes and let me know if everything looks OK. If so, I'll squash all the commits together and merge.

Thank you for your reply. The test on my device went smoothly. Here are the test results:

RECEIVE: | OK your-domain.dyn.la 108.61.1.1
SUCCESS: Successfully updated your-domain.dyn.la: good: IPv4 address set to 108.61.1.1
Can’t execute “sendmail”: No such file or directory at ./ddclient line 2384.
WARNING: Cannot execute command | sendmail -oi root.

**Pull request merged**
