### PR TITLE
IPv6 framework + Cloudflare + FreeDNS

### PR DESCRIPTION
**Pull request by dkerr64**
There is no way to add IPv6 support in piece parts so here goes...

Following guidance in the design document #163 and issue #172 ...

1. Added all the options and data structures needed, marking those old ones as deprecated. 
2. Added new `get_ipv4()` and `get_ipv6()` functions
3. Updated `test_possible_ips()` function to add IPv4 and IPv6
4. Updated `run_postscript()` function to pass both IPv4 and IPv6
5. Updates to `write_cache()` and `init_config()` to support IPv4 and IPv6
6. Updated `update_nics()` and `nic_updatable()` functions for IPv4 and IPv6
7. Added `max-warn` option to prevent flooding syslog with warnings because we may be only updating one of IPv6 or IPv4 and not both.

And...
Updated **Cloudflare** and **FreeDNS** functions to work with the new framework.  All other services will continue to work with the old and can be updated over time, but I needed to include one or two in this PR so it can be tested.

Note that config option `ipv6` changes from `T_BOOL` to `T_IPV6`.  This is only (that I am aware of) potential conflict with existing usage.

Requires **review and testing** by more than just me.

### CODE REVIEW

**Comment by DivineDominion** [comment]
Some feedback: I get no errors when I use the `usev6=ip,...` setting, but it also doesn't do anything with dynv6.net (dyndns2 protocol), not even output errors or warnings in `-debug -verbose -noquiet` mode, which is strange.

**Comment by dkerr64** [comment]
@DivineDominion right... for this PR I just implemented Cloudflare and FreeDNS.  Once this is merged I can work on the other services, but to do them in this PR would make it much larger than it already is.  So to facilitate code review and testing I wanted to keep it simple.

But this has been sitting for a couple of months now so it would be nice to hear from @SuperSandro2000 in prospects for merging.

**Comment by DivineDominion** [comment]
@dkerr64 From what I've heard it's _supposed_ to work with Dynv6; but maybe I'm reporting totally irrelevant stuff here and don't notice, sorry :)

**Comment by SuperSandro2000** [comment]
> Requires review and testing by more than just me.

I don't really have the motivation to extensively test this right now which is why I didn't merge it yet.

**Comment by tibbsbrookside** [comment]
Not sure if this helps but, just thought I'd say that I've tested this build with FreeDNS using both ifv6 and webv6 and it appears to work OK. I do get the following warnings but I'm not sure if they are related:

> WARNING:  '' is not a valid IPv4 or IPv6 address
WARNING:  found neither IPv4 nor IPv6 address
WARNING:  {HOST}: unable to determine IP address with strategy use=ip

**Comment by adarobin** [comment]
I've used this successfully with CloudFlare.  IPv4 and IPv6 records are updated (assuming they already exist in CloudFlare).

```
daemon=600
syslog=yes
#ssl=yes

protocol=cloudflare
use=web
usev6=ifv6
ifv6=ens192
password=REDACTED_TOKEN
zone=redacted.net
minecraft.redacted.net
```

**Comment by Neustradamus** [comment]
Any news?

**Comment by dkerr64** [comment]
@DaveSophoServices thank you.  I'll be testing it.

**Pull request merged**
