### PR TITLE
inwx: Add missing `hostname` argument to update URL

### PR DESCRIPTION
**Pull request by rhansen**
@Starkstromkonsument Does this look correct to you?  If so, would you please test it?

### CODE REVIEW

**Comment by Starkstromkonsument** [comment]
Hi, INWX does not need / support the `hostname` argument. They only support these arguments in their Update-URL: `https://dyndns.inwx.com/nic/update?myip=<ipaddr>&myipv6=<ip6addr>`.

Background: Each hostname has its own DynDNS-Account with an own combination of username/password. Here is a screenshot of their add account dialog:

IMG_20240729_072604

**Comment by Starkstromkonsument** [comment]
The hostname can not be changed:

IMG_20240729_073335

**Comment by rhansen** [comment]
Thanks for the info!  I'll add a comment.

I really wish they would document their API...

**Comment by Starkstromkonsument** [comment]
> I really wish they would document their API...

Me too! But they actually have an alternative [XML-RPC / JSON-RPC API](https://www.inwx.de/en/offer/api) for complete DNS management, that is properly documented. It could be used for DynDNS too, but that would be way more complicated and exceeds my capabilities.

There are some ready to use implementations for it e.g. [libdns](https://github.com/libdns/inwx). Maybe adding support for an interface to libdns or something similar would be something for a future roadmap for ddclient?

**Pull request closed without merging**
