### PR TITLE
Add FreeBSD; change README to use json-pp for Ubuntu

### PR DESCRIPTION
**Pull request by thorsteneb**
Tested on FreeBSD 11.3; expected to work on 12.1 as well.

### CODE REVIEW

**Comment by rhansen** [comment]
Thank you!

**Comment by SuperSandro2000** [comment]
There is no up to date FreeBSD Docker container so we can't add tests for it.

**Comment by thorsteneb** [comment]
That is a good point, @SuperSandro2000 , and I now remember that I did need to make a change to the ddclient script as distributed: It starts with a shebang for /usr/bin/perl as well as /usr/local/bin/perl. This will cause it to fail on FreeBSD 11.3, it's necessary to remove that first line. After that, it works.

**Comment by rhansen** [comment]
> It starts with a shebang for /usr/bin/perl as well as /usr/local/bin/perl. This will cause it to fail on FreeBSD 11.3, it's necessary to remove that first line. After that, it works.

This has recently changed: We now use GNU Autoconf to locate the `perl` executable, and `make` replaces the path in the shebang line, so it should just work on FreeBSD.

**Pull request merged**
