### PR TITLE
porkbun: rework logic to allow for simultaneous update of IPv4 and IPv6

### PR DESCRIPTION
**Pull request by TinfoilSubmarine**
Just had a look at the diff and it was not too obvious what I did, so here's the gist:

- Update porkbun logic to properly handle dual updates to IPv4 and IPv6 at one time
- Also slightly deduplicated the porkbun logic by unifying the ipv4 and ipv6 logic using `$ipv`

### CODE REVIEW

**Comment by LenardHess** [comment]
From a quick glimpse of the old code - it doesn't seem like simultaneous IPv4 and IPv6 was broken?

Cleanup/Refactor looks good to me though :+1: 

I assume you're using porkbun and tested this?

**Comment by TinfoilSubmarine** [comment]
> From a quick glimpse of the old code - it doesn't seem like simultaneous IPv4 and IPv6 was broken?

That's what I was confused about, but I think that the `next` calls were messing it up. I didn't verify that this was true though.
> Cleanup/Refactor looks good to me though 👍
> 
> I assume you're using porkbun and tested this?
Yes, testing it out directly on the Porkbun API with multiple domains, root domain, etc.

**Comment by TinfoilSubmarine** [comment]
OK, sorry for another set of revisions to the commit, but I didn't like the addition of the extra function when the same thing could be accomplished with a foreach. Logic remains the same.

**Comment by LenardHess** [comment]
Thanks for the update!

We will leave this pull request open until v3.11.0 has been released (see https://github.com/ddclient/ddclient/issues/552#issuecomment-1675925270 for details). It will get pulled into v3.11.1

**Comment by LenardHess** [comment]
With v3.11.0 released, please rebase ontop of current master.

**Pull request merged**
