### PR TITLE
systemd.service unit file improvements

### LINKED ISSUE #655: systemd logs
why logs aren't going to journalctl ?

we got log=syslog , I think ddclient don't have log=systemd ?  as I saw in a few projects

### PR DESCRIPTION
**Pull request by rhansen**
Fixes #655

### CODE REVIEW

**Comment by rhansen** [comment]
FYI @sergiomb2

**Comment by sergiomb2** [comment]
[/usr/lib/systemd/system/ddclient.service:8] Failed to parse service type, ignoring: exec

**Comment by sergiomb2** [comment]
with:  `Type=simple` works

**Comment by rhansen** [comment]
Are you using an old version of systemd?  `exec`
should work:  https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html
(`simple` is also acceptable)

**Comment by sergiomb2** [comment]
Centos 7

**Comment by rhansen** [comment]
CentOS 7 has an old version of systemd, before `exec` was added (in v240).  `simple` is also acceptable.

(Sorry for the comment churn; the GitHub app appears to be buggy.)

**Pull request merged**
