### PR TITLE
Whitespace fixes

### PR DESCRIPTION
**Pull request by rhansen**
Use consistent indentation and vertical alignment.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
We are still mixing tab and spaces. Could you fix this, too? Thanks!

**Comment by rhansen** [comment]
The indentation width is 4 columns, and tab width is assumed to be 8. Thus, one level of indentation will get 4 spaces, two levels of indentation will get a tab, three levels of indentation will get a tab and 4 spaces, and so on.

My personal preference is to use spaces instead of tabs, but the existing convention was to use tabs so I preserved that. Would you like me to convert all tabs to spaces?

**Comment by rhansen** [comment]
(Also, I don't know if you saw my comments on PR #116 and #117 about squashing. Please take a look.)

**Comment by SuperSandro2000** [comment]
> (Also, I don't know if you saw my comments on PR #116 and #117 about squashing. Please take a look.)

Yeah, you are totally right. Just bad habit I got used to from dependabot.

**Comment by rhansen** [comment]
I converted tabs to spaces and rebased the branch onto current `master`.

**Comment by SuperSandro2000** [comment]
First time i used the GitHub conflict resolution tool on the web and if I had known that it merges master into this PR I would have done it manually. I guess I learned something new.

If we decide we do not like the new formatting I think we need to agree on some formatting tool. Before this I think it was a bit chaotic and a cleanup helped.

**Comment by rhansen** [comment]
> First time i used the GitHub conflict resolution tool on the web and if I had known that it merges master into this PR I would have done it manually. I guess I learned something new.

Huh, that's good to know.

> If we decide we do not like the new formatting I think we need to agree on some formatting tool.

Agreed. It would be worth mentioning a formatting command in a contributor guide.

I used this [perltidy](https://metacpan.org/pod/perltidy) command to help me with this PR:

    perltidy -l=0 -conv -ci=4 -ola -ce -nbbc -kis -pt=2 -o=ddclient.new ddclient

**Comment by rhansen** [comment]
By the way, thank you for all of the quick merges!

**Comment by SuperSandro2000** [comment]
No problem. You do really nice rebiewab pull requests. I'll put that format command in a contributions guide or pull request tomorrow to remind people to format their code like this.

**Pull request merged**
