### PR TITLE
Fix detection of `get_ip` caller

### PR DESCRIPTION
**Pull request by rhansen**
This was broken in f6f920eb3971a0d239b564fb53d7176e97ece9be.

### CODE REVIEW

**Comment by dkerr64** [comment]
That section of code is quite cryptic.  I might suggest the following cleanup...
```
debug("opt(fw = %s)", opt('fw')) if opt('fw');
debug("glo fw = %s", $globals{'fw'}) if $globals{'fw'};
## always omit SSL for connections to local router
my $is_get_ip = (((caller(1))[3] // '') eq 'ddclient::get_ip');
if ($force_ssl || ($globals{'ssl'} && !$is_get_ip)) {
   ## etc
}
```
The reason to create a $`is_get_ip` is because we will need to also test for `ddclient::get_ipv4` and `ddclient::get_ipv6` once that code is merged (I have it ready and waiting... pending my other PRs getting merged first).  So it will just make it much easier to understand... and I also want to use `$is_get_ip` later in my curl implementation, so I need the test twice.

**Comment by dkerr64** [comment]
Oh... and doing `debug() if xyz` is so much clearer than `xyz && debug()`. At least to my eyes.

**Comment by rhansen** [comment]
> That section of code is quite cryptic. I might suggest the following cleanup...

I took a different approach; please take another look.

> Oh... and doing `debug() if xyz` is so much clearer than `xyz && debug()`.

Agreed, but out of scope for this PR.

**Comment by dkerr64** [comment]
> > That section of code is quite cryptic. I might suggest the following cleanup...
> 
> I took a different approach; please take another look.

Yes, your approach is better.

> 
> > Oh... and doing `debug() if xyz` is so much clearer than `xyz && debug()`.
> 
> Agreed, but out of scope for this PR.

And again you found a better answer but just deleting them.

**Comment by rhansen** [comment]
Thanks for the review!

**Pull request merged**
