### PR TITLE
Fix handling of legacy `status` with IPv6-aware protocols

### LINKED ISSUE #554: Providers: fix various old caching issues
Some providers have improper implementations with regards to caching. It seems that these implementations never did right in the first place.

These fixes are not required for the v3.11 release, that was handled in rrthomas/ddclient#10 .

Providers without proper cache parameter implementation:
- [ ] 1984
- [ ] Njalla
- [x] nsupdate

### LINKED ISSUE #631: ddclient v3.11.2/opnsense plugin os-ddclient v1.21 - ddclient updates GoDaddy DNS entry every 300s even if dynamic IP has not changed
Hi there,

I am submitting this issue after unsuccessfully resolving it via the opnsense/plugins/os-ddclient repository: [https://github.com/opnsense/plugins/issues/3805](https://github.com/opnsense/plugins/issues/3805)

To be frank, things unfortunately escalated there, after I criticized the -from my point of view- lack of support. So, to prevent repeating any potential mistakes made, I would like to state upfront:

- I am not a technical expert, my skills are limited
- I am a very happy home user of opnsense and ddclient
- I seek support and help here to solve my problem and hopefully contribute a bit to solving it for the rest of the community
- I am very grateful for any help given

In order to limit the redundancies, I will just copy and paste the description of the issue here. More detailed information is to be found in the link above.

**Describe the bug**

I just changed my ddclient from using FreeDNS to using GoDaddy. The dynamic ip has been checked properly (via Interface/WAN) and the respective GoDaddy DNS entry has been updated correctly. However, ddclient now seems to "statically/periodically" update the GoDaddy DNS entry every 300 seconds (as configured in ddclient's general settings), even if the dynamic ip has not changed.

ddclient using GoDaddy now shows a different behavior compared to using FreeDNS. Using FreeDNS, the DNS entry was only updated if the dynamic IP had been changed by the provider.

Best regards!

### PR DESCRIPTION
**Pull request by rhansen**
Fixes #554
Fixes #631

### CODE REVIEW

**Comment by rhansen** [comment]
@phaze75 Would you please try this to see if it fixes your issue?

**Comment by phaze75** [comment]
> @phaze75 Would you please try this to see if it fixes your issue?

@rhansen I would like to try it out. But I have no development skills whatsoever, so I also have no idea how to compile the code to try it out. ddclient is "just" a package of my OPNsense firewall (OPNsense 24.1.7-amd64, FreeBSD 13.2-RELEASE-p11). I just installed it by clicking on it. ;-) However, I can handle the system on command line level.

So, if I should try this, I would need dummy step by step instructions how to do it. ;-)

**Comment by rhansen** [comment]
@phaze75 Try these steps:

  1. Click on the [Checks](https://github.com/ddclient/ddclient/pull/670/checks) tab in this PR
  2. Just above the big black log output section there's an "Artifacts" drop-down.  Click it.
  3. Download the `distribution-tarball` artifact
  4. Open `distribution-tarball.zip` and extract `ddclient-3.11.3~alpha.tar.gz` (yes, it's awkward that there's an archive inside an archive, that's due to a GitHub limitation)
  5. Copy `ddclient-3.11.3~alpha.tar.gz` to your OPNsense firewall
  6. Extract the tarball.  Something like:
      ```sh
      cd /tmp
      tar xvfa /path/to/ddclient-3.11.3~alpha.tar.gz
      ```
  7. Build:
      ```sh
      cd ddclient-3.11.3~alpha
      ./configure
      make
      ```
  8. Overwrite the existing `ddclient` script:
      ```sh
      cp ddclient /path/to/your/existing/ddclient
      ```
  9. Restart ddclient

**Comment by phaze75** [comment]
@rhansen Thanks a lot, I successfully managed to compile and replace the ddclient file. Unfortunately, GoDaddy meanwhile denies my access via API (maybe due to the excessive updates). I just became aware of the errors in the log. I tried to renew the API key and secret, but no success. So, I opened a support case.

**Comment by phaze75** [comment]
@rhansen Unfortunately the claims in Reddit were correct. I just received the official answer by GoDaddy:

> We have recently updated the account requirements to access parts of our production Domains API. As part of this update, access to these APIs are now limited:
>•	Availability API: Limited to accounts with 50 or more domains
>•	Management and DNS APIs: Limited to accounts with 10 or more domains and/or an active Premium Discount Domain Club plan.

As I have only a single domain, I cannot use or test the GoDaddy API anymore. Sorry! Thank you for your support!

**Comment by rhansen** [comment]
Thanks for following up.  I'll go ahead and merge this and hope that someone will speak up if it breaks something.  :wink:

**Pull request merged**
